[package]
name = "bigint"
description = "Virtual Machine for Ninja"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[build-dependencies]
bindgen = "0.71.1"
