[package]
name = "njvm"
version = "0.4.0"
edition = "2021"
license = "MIT"
authors = ["Clemens Horn <clemens.horn@mni.thm.de>"]
description = "Virtual Machine for Ninja"

[dev-dependencies]
assert_cmd = "2.0.16"
anyhow = "1.0.95"
predicates = "3.1.3"
difference = "2.0.0"
