#!/bin/sh

TARGET="x86_64-unknown-linux-gnu"

cargo fmt --all -- --check &&
cargo clippy --release --target $TARGET -- -D warnings && 
cargo build --release --target $TARGET --locked && 
cargo test --workspace --release --target $TARGET && 

cp target/$TARGET/release/njvm njvm
