[package]
name = "njvm-cli"
description = "CLI for the Ninja Virtual Machine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap.workspace = true
